### ISSUE TITLE
Host removed after redirect

### ISSUE THREAD

**Issue by fr-edy** [sleeyax/gotcha#2]
Hey, I like your respository a lot! I was wondering if you could add an option to not delete the sensitive headers like "host" after a redirect to another host?

Thank you very much in advance :)

**Comment by sleeyax** [comment]
Did you solve this or? Just checking in. Maybe you can share your solution so others who stumble upon this issue can benefit from it as well.

**Comment by fr-edy** [comment]
Just don't set the host header and let the http client set it itself.
